name: "Release CI"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows
      - name: Release to GitHub
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: "${{ github.event.pusher.name }}"
          GIT_AUTHOR_EMAIL: "${{ github.event.pusher.email }}"
          GIT_COMMITTER_NAME: "${{ github.event.pusher.name }}"
          GIT_COMMITTER_EMAIL: "${{ github.event.pusher.email }}"
        run: npx semantic-release